### ISSUE TITLE
highlight in legend is persistent when I update the data

### ISSUE THREAD

**Issue by cnavarreteliz** [d3plus/d3plus-viz#120]
![Jun-04-2019 17-05-59](https://user-images.githubusercontent.com/5233593/58913890-39ff9b00-86eb-11e9-8ebd-c8fc6ef88e59.gif)

### Expected Behavior

I would like to reset the `highlight` option where I update the data.

### Current Behavior

highlight in legend is persistent when I update the data used in the visualization

### Steps to Reproduce (for bugs)

1. Go to [https://data.stat.ee](https://data.stat.ee)
2. Highlight in any Chapter
3. Update `DEPTH` selector

### Your Environment

* Browser Name:
* Operating System and Version:

**Comment by davelandry** [comment]
@cnavarreteliz the [legend click behavior](https://github.com/d3plus/d3plus-viz/blob/master/src/on/click.legend.js) sets two internal properties: `this._solo` and `this._hidden`. The fix for this _should_ be as easy as adding these lines to [the data method](https://github.com/d3plus/d3plus-viz/blob/master/src/Viz.js#L823):

```js
this._solo = [];
this._hidden = [];
```
