### ISSUE TITLE
legend click behaviors arent working on 1.2.4

### ISSUE THREAD

**Issue by AlanORB** [d3plus/d3plus-viz#175]
https://jsfiddle.net/AlanORB/8a0pn6qm/4/

**Comment by davelandry** [comment]
I cut a new release of the big compiled [d3plus package](https://cdn.jsdelivr.net/npm/d3plus@2) we use in fiddles, and I'm still not able to recreate this bug.

@AlanORB please spend some time with your fiddle trying to recreate the problem you were seeing in InsightsCloud. Here are the main things I try to do when bug hunting in d3plus:
1. Copy/paste in as many `config` methods that exist in order to reproduce the bug in jsfiddle (methods in both the CMS config and the d3plus.js config may be the culprit).
2. Once you have recreated the bug in jsfiddle, remove all uneffected/unrelated `config` methods from the fiddle. For example, your jsfiddle has `title` and `legendPosition` methods, which I would assume do not effect the data processing or the click events.
3. Remove as many data points as possible from your data array so that the bug still happens with the least amount of data (the smaller the data, the easier it is to debug and scroll).

**Comment by davelandry** [comment]
Solution was to upgrade to v1.2.5
