### ISSUE TITLE
click events on iOS safari are not registering

### ISSUE THREAD

**Issue by jspeis** [d3plus/d3plus-viz#62]
When trying to register click events in Safari, using `on` via `click.shape`, the target callback doesn't happen.

### Expected Behavior
The `click.shape` callback should be triggered on iOS Safari

### Current Behavior
Tooltips will appear but not click events
### Steps to Reproduce (for bugs)

1. Open https://jsfiddle.net/jonathan_dw/jdbn220u/19/
2. Try to click a state (if clicked, an alert box should appear)

**Comment by davelandry** [comment]
@jspeis I looked into this, and it turns out you need to also check for "touchstart": https://jsfiddle.net/jdbn220u/29/

I just published a release of `d3plus-common`, where we prep the mouse event behaviors, to add that to any click event passed by the user. In the meanwhile, you guys should be able to add it manually to get it to work.
